msm: fix in-tree compilation for perf_trace_counters
In-tree compilation for arch/arm/mach-msm/perf_trace_counters.c was
hitting this error:

    In file included from arch/arm/mach-msm/perf_trace_counters.h:127:0,
                     from arch/arm/mach-msm/perf_trace_counters.c:14:
    include/trace/define_trace.h:79:43: fatal error: ./perf_trace_counters.h: No such file or directory

Instructions for TRACE_INCLUDE_FILE in include/trace/define_trace.h say
"the path is relative to define_trace.h, not the file including it".
Fix in-tree compilation by making the path relative to define_trace.h.

Change-Id: I566b83faf2714ce5f68ac11e5d63ab7cd0de23ed
Signed-off-by: Bryan Huntsman <bryanh@codeaurora.org>

Conflicts:
	arch/arm/mach-msm/perf_trace_counters.h